name: Computer engineer, Web applications, Back-end and Front-end Development
title: Adam Raya
tagline: Freelance Developer
description: "Adam Raya, Computer engineer, working with Web applications, Back-end and Front-end Development and Mobile applications."
author: adamraya
url: "http://adamraya.com"
baseurl: /
paginate: 5

markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Permalinks
permalink:        pretty
relative_permalinks: true
